library(SeuratDisk)
library(Seurat)

Contra1 <- read.table('../outs/20231128_Intact_Contra/NCBI.Contra1.sc.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Contra1)) -> rownames(Contra1)
Contra1_so <- CreateSeuratObject(counts = Contra1, min.cells = 0, min.genes = 0, project = "Contra")
saveRDS(Contra1_so, file = "../outs/20231128_Intact_Contra/Contra1.reform.rds")
SaveH5Seurat(Contra1_so, filename = "../outs/20231128_Intact_Contra/Contra1.reform.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Contra1.reform.h5Seurat", dest = "h5ad")

Contra2 <- read.table('../outs/20231128_Intact_Contra/NCBI.Contra2.sc.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Contra2)) -> rownames(Contra2)
Contra2_so <- CreateSeuratObject(counts = Contra2, min.cells = 0, min.genes = 0, project = "Contra2")
saveRDS(Contra2_so, file = "../outs/20231128_Intact_Contra/Contra2.reform.rds")
SaveH5Seurat(Contra2_so, filename = "../outs/20231128_Intact_Contra/Contra2.reform.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Contra2.reform.h5Seurat", dest = "h5ad")

Contra3 <- read.table('../outs/20231128_Intact_Contra/NCBI.Contra3.sc.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Contra3)) -> rownames(Contra3)
Contra3_so <- CreateSeuratObject(counts = Contra3, min.cells = 0, min.genes = 0, project = "Contra3")
saveRDS(Contra3_so, file = "../outs/20231128_Intact_Contra/Contra3.reform.rds")
SaveH5Seurat(Contra3_so, filename = "../outs/20231128_Intact_Contra/Contra3.reform.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Contra3.reform.h5Seurat", dest = "h5ad")

Intact1 <- read.table('../outs/20231128_Intact_Contra/NCBI.Intact1.sc.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Intact1)) -> rownames(Intact1)
Intact1_so <- CreateSeuratObject(counts = Intact1, min.cells = 0, min.genes = 0, project = "Intact1")
saveRDS(Intact1_so, file = "../outs/20231128_Intact_Contra/Intact1.reform.rds")
SaveH5Seurat(Intact1_so, filename = "../outs/20231128_Intact_Contra/Intact1.reform.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Intact1.reform.h5Seurat", dest = "h5ad")

Intact2 <- read.table('../outs/20231128_Intact_Contra/NCBI.Intact2.sc.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Intact2)) -> rownames(Intact2)
Intact2_so <- CreateSeuratObject(counts = Intact2, min.cells = 0, min.genes = 0, project = "Intact2")
saveRDS(Intact2_so, file = "../outs/20231128_Intact_Contra/Intact2.reform.rds")
SaveH5Seurat(Intact2_so, filename = "../outs/20231128_Intact_Contra/Intact2.reform.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Intact2.reform.h5Seurat", dest = "h5ad")

Contra1 <- read.table('../outs/20231128_Intact_Contra/NCBI.Contra1.sc.summed.gene.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Contra1)) -> rownames(Contra1)
Contra1_so <- CreateSeuratObject(counts = Contra1, min.cells = 0, min.genes = 0, project = "Contra")
saveRDS(Contra1_so, file = "../outs/20231128_Intact_Contra/Contra1.summed.rds")
SaveH5Seurat(Contra1_so, filename = "../outs/20231128_Intact_Contra/Contra1.summed.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Contra1.summed.h5Seurat", dest = "h5ad")

Contra2 <- read.table('../outs/20231128_Intact_Contra/NCBI.Contra2.sc.summed.gene.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Contra2)) -> rownames(Contra2)
Contra2_so <- CreateSeuratObject(counts = Contra2, min.cells = 0, min.genes = 0, project = "Contra2")
saveRDS(Contra2_so, file = "../outs/20231128_Intact_Contra/Contra2.summed.rds")
SaveH5Seurat(Contra2_so, filename = "../outs/20231128_Intact_Contra/Contra2.summed.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Contra2.summed.h5Seurat", dest = "h5ad")

Contra3 <- read.table('../outs/20231128_Intact_Contra/NCBI.Contra3.sc.summed.gene.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Contra3)) -> rownames(Contra3)
Contra3_so <- CreateSeuratObject(counts = Contra3, min.cells = 0, min.genes = 0, project = "Contra3")
saveRDS(Contra3_so, file = "../outs/20231128_Intact_Contra/Contra3.summed.rds")
SaveH5Seurat(Contra3_so, filename = "../outs/20231128_Intact_Contra/Contra3.summed.h5Seurat")
Convert("../outs/20231128_Intact_Contra/Contra3.summed.h5Seurat", dest = "h5ad")

Intact1 <- read.table('../outs/20231128_Intact_Contra/NCBI.Intact1.sc.summed.gene.counts.matrix', sep = '\t', header = T, row.names = 1)
make.names(rownames(Intact1)) -> rownames(Intact1)
Intact1_so <- CreateSeuratObject(counts = Intact1, min.cells = 0, min.genes = 0, project = "Intact1")
